apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: refus-par-defaut
spec:
  podSelector: {}
  policyTypes: [Ingress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: applications-depuis-entree
spec:
  podSelector:
    matchExpressions:
      - { key: app, operator: In, values: [backoffice, backend] }
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels: { kubernetes.io/metadata.name: ingress-nginx }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ia-depuis-backend
spec:
  podSelector:
    matchLabels: { app: ai-service }
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels: { app: backend }
