apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice
  template:
    metadata:
      labels:
        app: backoffice
    spec:
      containers:
        - name: backoffice
          image: parkree-backoffice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backoffice
spec:
  selector:
    app: backoffice
  ports:
    - port: 80
      targetPort: 80