spring.application.name=backend
spring.mongodb.uri=${MONGODB_URI}

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.health.mongo.enabled=false

aiservice.url=${AI_SERVICE_URL:http://localhost:8000}

server.port=${PORT:8080}
allowed.origins=${ALLOWED_ORIGINS:http://localhost:4200}